variable "name" {}
variable "location" {}
variable "vnetcidr" {}
variable "websubnetcidr" {}
variable "appsubnetcidr" {}
variable "dbsubnetcidr" {}
variable "web_host_name" {}
variable "web_username" {}
variable "web_os_password" {}
variable "app_host_name" {}
variable "app_username" {}
variable "app_os_password" {}
variable "primary_database" {}
variable "primary_database_admin" {}
variable "primary_database_password" {}
variable "primary_database_version" {}
variable "sa_name" {}
variable "sa_rg_name" {}
variable "sa_location" {}
variable "sa_acc_tier" {}
variable "sa_acc_repl_type" {}
variable "sa_env" {}
